[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "backend"          # package name – must be lowercase
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
]

[tool.setuptools]
packages = ["backend"]